package com.project.main.autohome.model.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import com.project.main.autohome.util.ImageLoaderUtil;

/**
 * Entity mapped to table "AUTO_HOME_BEAN".
 *
 * 实体类
 */
public class AutoHomeBean {

    private Long id;
    private String title;
    private String content;
    private String price;
    private String imageUrl;
    private String Url;
    private String info;
    private String classify;

    public AutoHomeBean() {
        ImageLoaderUtil.getInstance();
        ImageLoaderUtil.getInstance();
        ImageLoaderUtil.getInstance();
        ImageLoaderUtil.getInstance(); ImageLoaderUtil.getInstance(); ImageLoaderUtil.getInstance();


    }

    public AutoHomeBean(Long id) {
        this.id = id;
    }

    public AutoHomeBean(String title, String price, String imageUrl, String url, String content, String info, String classify) {
        this.title = title;
        this.price = price;
        this.imageUrl = imageUrl;
        Url = url;
        this.content = content;
        this.info = info;
        this.classify = classify;
    }

    public AutoHomeBean(Long id, String title, String content, String price, String imageUrl, String Url, String info, String classify) {
        this.id = id;
        this.title = title;
        this.content = content;
        this.price = price;
        this.imageUrl = imageUrl;
        this.Url = Url;
        this.info = info;
        this.classify = classify;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getPrice() {
        return price;
    }

    public void setPrice(String price) {
        this.price = price;
    }

    public String getImageUrl() {
        return imageUrl;
    }

    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    public String getUrl() {
        return Url;
    }

    public void setUrl(String Url) {
        this.Url = Url;
    }

    public String getInfo() {
        return info;
    }

    public void setInfo(String info) {
        this.info = info;
    }

    public String getClassify() {
        return classify;
    }

    public void setClassify(String classify) {
        this.classify = classify;
    }

}
