package com.project.main.autohome.model.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.project.main.autohome.model.db.AutoHomeBean;

import com.project.main.autohome.model.db.AutoHomeBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig autoHomeBeanDaoConfig;

    private final AutoHomeBeanDao autoHomeBeanDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        autoHomeBeanDaoConfig = daoConfigMap.get(AutoHomeBeanDao.class).clone();
        autoHomeBeanDaoConfig.initIdentityScope(type);

        autoHomeBeanDao = new AutoHomeBeanDao(autoHomeBeanDaoConfig, this);

        registerDao(AutoHomeBean.class, autoHomeBeanDao);
    }
    
    public void clear() {
        autoHomeBeanDaoConfig.getIdentityScope().clear();
    }

    public AutoHomeBeanDao getAutoHomeBeanDao() {
        return autoHomeBeanDao;
    }

}
